{"data": "Traceback (most recent call last):\n  File \"/Users/akrah/Documents/dev/SemEval22/clozetask/utils/zlog.py\", line 39, in log_context\n    yield self\n  File \"/Users/akrah/Documents/dev/SemEval22/clozetask/management/runscript.py\", line 138, in run_loop\n    runner = setup_runner(\n  File \"/Users/akrah/Documents/dev/SemEval22/clozetask/management/runscript.py\", line 119, in setup_runner\n    runner = semeval_runner.TaskRunner(\nTypeError: __init__() got an unexpected keyword argument 'jiant_task_container'\n", "TIMESTAMP": 1638133737.809396}
